### ISSUE TITLE
Shkeeper can't connect to LTC and DOGE when in testnet mode

### ISSUE THREAD

**Issue by dmytro-samoylenko** [vsys-host/helm-charts#6]
```
root@shkeeper-test-doge-testnet:~# cat values.yaml
storageClassName: local-path

btc:
  enabled: false
ltc:
  enabled: true
  mainnet: false
doge:
  enabled: true
  mainnet: false
```

https://github.com/vsys-host/shkeeper.io/issues/94

In the result both litecoind and dogecoind are synced to blockchain, but can't accept json-rpc request due to authentication error.

The root cause: both litecoind and dogecoind are using rpc login and password passed as environment variables in k8s deployment (e.g. $DOGE_USERNAME, $DOGE_PASSWORD), but due to syntax error credentials isn't taken from ENV, but literals strings `$DOGE_USERNAME` and `$DOGE_PASSWORD` are being used as rpc login and password.

Fix: change `$VAR` to `$(VAR)`, e.g:

https://github.com/vsys-host/helm-charts/blob/main/charts/shkeeper/templates/deployments/dogecoind.yaml#L48

```
        - -rpcpassword=$DOGE_PASSWORD
        - -rpcuser=$DOGE_USERNAME
```

these should be changed to:

```
        - -rpcpassword=$(DOGE_PASSWORD)
        - -rpcuser=$(DOGE_USERNAME)
```
